spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_MYSQL}
    username: zuper
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:transacao-api}
      auto-offset-reset: ${KAFKA_AUTO-OFFSET-RESET:latest}
    topic:
      transactions: ${KAFKA_CONSUMER_TOPIC:transacoes}
